version: '3'
services:
  membership-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:mypostgresqlpassword@db/eha-membership"
    env_file:
      - .env
    command: ["npm", "start", "--host", "0.0.0.0", "--port", "3000"]

  db:
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypostgresqlpassword
      POSTGRES_DB: geewallet
